Centos minimal 8
switch-ch/diskimage-builder pull request #16
Opened 2020-01-29 08:29 UTC by Happy2C0de

Add support for Centos8.

2020-01-30 10:06 UTC, valerytschopp commented
@Happy2C0de unfortunately I can not merge this in the SWITCHengines branch

The SWITCHengines branch is NOT on upstream master, but on tag 2.33.0 (commit 3a7d4528a06b553170e968e6fb8c187433548e15), but your branch is on master... So if I merge this it can create havoc.

Can you rebase your branch on the SWITCH switch-ch/diskimage-builder SWITCHengines branch?

```
git remote add switch https://github.com/switch-ch/diskimage-builder.git
git fetch --all
git checkout centos-minimal-8 
git status
git rebase switch/SWITCHengines
git status
git pull
git status
git diff switch/SWITCHengines
```

2020-01-30 10:07 UTC, valerytschopp commented
@Happy2C0de a better branch name: `centos8`

2020-01-30 10:42 UTC, valerytschopp commented
And can you add the `rm /etc/motd.d/cockpit` somewhere?

2020-01-31 07:17 UTC, Happy2C0de commented
I rebased the branch and added a comment about the WebConsole. Furthermore, a note how one can remove the notification is in the CentOS 8 README.

2020-01-31 07:19 UTC, Happy2C0de commented
A renaming of the branch closes the PR and I must create a new one. Does this make sense? I would keep it. Because the current name is not completely off the track.

2020-01-31 09:58 UTC, valerytschopp commented
Nice, with the rebase, only 16 files have changed, compared to 122 before ;)

And it is ok to keep this branch name.

But personally, I would prefer to `rm /etc/motd.d/cockpit`. Experienced users know about Cockpit already, so they can enable it if they want. But unexperienced users will enable, set a bad user password, open the firewall, and will get hacked...

2020-01-31 09:59 UTC, valerytschopp commented
Did you try to build a image with the rebased branch? Does it still work?

2020-01-31 10:11 UTC, valerytschopp requested changes

2020-01-31 10:11 UTC, valerytschopp commented on diskimage_builder/elements/centos8/post-install.d/23-cloud-init-default-user
> +        sed -i -e 's/cloud-user/'$DIB_CLOUD_INIT_DEFAULT_USER'/g' /etc/cloud/cloud.cfg
Here the sed match is very broad. 

You should match `name: cloud-user` and replace by `name: $DIB_CLOUD_INIT_DEFAULT_USER` e.g.:

`sed -i -e "s/name: cloud-user/name: $DIB_CLOUD_INIT_DEFAULT_USER/g" /etc/cloud/cloud.cfg`

2020-01-31 10:34 UTC, valerytschopp approved these changes
Thanks

2020-01-31 10:54 UTC, Happy2C0de commented
Branch was tested. Current branch works as expected. No ssh notification anymore and centos name works. 
Basic testing as mentioned here, https://wiki.smap.switch.ch/topic/switchcloud/images:release_process#test_scripts , was conducted. (plus a bit more)

Ready to merge I guess. Don't see any obvious errors. Images are published in staging (s1 and s2)
I will push it to production once it is merged.

Thanks for reviewing! :)

2020-01-31 11:49 UTC, merged

2020-01-31 11:49 UTC, valerytschopp commented
Thanks Michael, excellent work!